const CONSTANTS = {
  FETCH_DATA: 'HOTELS/FETCH_DATA',
  FETCH_DATA_SUCCESS: 'HOTELS/FETCH_DATA_SUCCESS',
  FETCH_DATA_PENDING: 'HOTELS/FETCH_DATA_PENDING',
  FETCH_DATA_FAIL: 'HOTELS/FETCH_DATA_FAIL',
};

export default CONSTANTS;
